services:
  - type: web
    name: livros-api
    runtime: python
    buildCommand: echo "No build required"
    startCommand: python serve.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11